name: 'Start containers'
on:
    schedule:
        - cron: 0 7 * * *
jobs:
    turnON:
        runs-on: ubuntu-latest
        steps:
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: start container apps
          run: |
                az containerapp list --resource-group team1-job-app-shared-rg --environment team1-job-app-shared-env --query "[].name" -o tsv | while read app; do
                  az containerapp start --name "$app" --resource-group team1-job-app-shared-rg
                done